# create pipeline with some name
name: ci workflow for pythin app test
# Trigger -- when this pipeline should start
on:
  push:
    branches:
    - "main"

# jobs for performing operation
jobs:
  raj-python-app-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:  [ubuntu-latest,windows-latest,macos-latest]

    steps:
    - name: check python version on platform ${{ matrix.os}}
      run: python -V